### PR TITLE
chores: update dependencies to latest versions

### PR DESCRIPTION
**Pull request by lyca**
Just some updates to be compatible with the latest couchbase version.

### CODE REVIEW

**Comment by atjeff** [comment]
Hey @lyca! Thank you so much for your interest and pull request.

This package is unmaintained, and really should be archived at this point. Were you able to test this and are you sure there aren't any breaking changes?

**Comment by lyca** [comment]
This is definitely a breaking change, as couchbase is upgraded from v3 to v4. But according to semver its not a problem:
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
-- https://semver.org/spec/v0.1.0.html#spec-item-5

But if you plan to archive it, I will have a look at https://github.com/davidepellegatta/node-cache-manager-couchbase

On the testing side  it definitely would need some more integration tests.

**Comment by atjeff** [comment]
I'm fine to merge it 👍 I hope it works for you

**Comment by atjeff** [comment]
Released as v0.4.0 on NPM

**Comment by lyca** [comment]
Thanks a lot :+1:

**Pull request merged**
